# Generated by Django 2.0 on 2020-02-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hotel',
            field=models.IntegerField(default=0),
        ),
    ]
