# Generated by Django 2.0 on 2020-02-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200212_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hotel'),
        ),
    ]
