# Generated by Django 2.0 on 2020-02-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200212_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Hotel'),
        ),
    ]
