# Generated by Django 2.0 on 2020-02-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200212_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
