# Generated by Django 2.0 on 2020-02-17 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('count_of_floors', models.IntegerField()),
                ('count_of_numbers', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('house', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('count_of_rooms', models.PositiveIntegerField()),
                ('square', models.PositiveIntegerField()),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Resedent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('burn_date', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'мужской'), ('f', 'женский')], max_length=1)),
                ('phone_number', models.CharField(max_length=30)),
                ('pasport_seria', models.CharField(max_length=4)),
                ('pasport_number', models.CharField(max_length=6)),
                ('count_of_living', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='nomer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Nomer'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='resedent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Resedent'),
        ),
    ]
