# Generated by Django 2.0 on 2020-02-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='nomer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Nomer', verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='resedent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Resedent', verbose_name='Постоялец'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='count_of_floors',
            field=models.IntegerField(verbose_name='Кол-во этажей'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='count_of_numbers',
            field=models.IntegerField(verbose_name='Кол-во комнат'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='house',
            field=models.CharField(max_length=30, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='street',
            field=models.CharField(max_length=30, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='nomer',
            name='count_of_rooms',
            field=models.PositiveIntegerField(verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='nomer',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Hotel', verbose_name='Выберите отель'),
        ),
        migrations.AlterField(
            model_name='nomer',
            name='square',
            field=models.PositiveIntegerField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='resedent',
            name='count_of_living',
            field=models.IntegerField(default=0, verbose_name='Количество заселений'),
        ),
        migrations.AlterField(
            model_name='resedent',
            name='father_name',
            field=models.CharField(max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='resedent',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='resedent',
            name='gender',
            field=models.CharField(choices=[('m', 'мужской'), ('f', 'женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='resedent',
            name='pasport_number',
            field=models.CharField(max_length=6, verbose_name='Паспорт номер'),
        ),
        migrations.AlterField(
            model_name='resedent',
            name='pasport_seria',
            field=models.CharField(max_length=4, verbose_name='Паспорт серия'),
        ),
        migrations.AlterField(
            model_name='resedent',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='resedent',
            name='second_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
    ]
