# Generated by Django 2.0 on 2020-02-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200217_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resedent',
            name='burn_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
