# Generated by Django 2.0 on 2020-02-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200217_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomer',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер комнаты в гостинице'),
        ),
    ]
