# Generated by Django 2.0 on 2020-02-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200218_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='date_chekin',
            field=models.DateField(null=True, verbose_name='Дата заселения'),
        ),
    ]
