# Generated by Django 2.0 on 2020-02-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200219_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='date_checkout',
            field=models.DateField(null=True, verbose_name='Дата выселения'),
        ),
    ]
